image: frolvlad/alpine-java:jdk8-slim

services:
  - docker:dind

stages:
  - test
  - build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:

test:
  stage: test

  script:
    - ./gradlew build
    - ./gradlew test

  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 3 days

  tags:
    - server

build:
  stage: build

  image: docker:latest

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    - docker build --pull -t switaewon/server:latest .
    - docker push switaewon/server:latest

  tags:
    - server