language: java
jdk:
  - openjdk8

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# database
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"